name: Build and push container to Google Artifacts Registry
on:
  release:
    types: [created]
jobs:
  push-to-artifacts:
    name: Build and push image to GCP
    runs-on: ubuntu-latest
    env:
      image_name: bq-connector
      project_id: bqconnect-349116
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Get current version tag
        id: get_tag
        run: echo "::setoutput name=release_tag::${GITHUB_REF#refs/tags/}"

      - name: Authenticate GCP
        uses: google-github-actions/auth@v0
        with: 
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v0
    
      - name: Configure Docker client
        run: |-
          gcloud auth configure-docker --quiet 
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t $image_name:latest .

      - name: Push image to artifacts registry
        env:
          tag: ${{ steps.get_tag.outputs.release_tag }}
        run: |-
          echo 'Pushing tagged release: ${{ env.tag }}'
          docker tag $image_name:latest northamerica-northeast1-docker.pkg.dev/$project_id/bq-images/$image_name:latest
          docker tag $image_name:latest northamerica-northeast1-docker.pkg.dev/$project_id/bq-images/$image_name:${{ env.tag }}
          docker push northamerica-northeast1-docker.pkg.dev/$project_id/bq-images/$image_name:latest
          docker push northamerica-northeast1-docker.pkg.dev/$project_id/bq-images/$image_name:${{ env.tag }}
